[package]
name = "simplet2s-capi"
version = "0.1.5"
authors = ["Messense Lv <messense@icloud.com>"]

[dependencies.simplet2s]
version = "0.1"
path = "../"

[build-dependencies]
cbindgen = "0.4"

[lib]
name = "simplet2s"
crate-type = ["cdylib"]

[profile.release]
lto = true
